name: PR Checks
on:
  pull_request:
    branches: [master]

jobs:
  test-reigns:
    name: Test reigns
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install reigns dependencies
        working-directory: ./elements/reigns
        run: npm i

      - name: Test reigns
        working-directory: ./elements/reigns
        run: npm run test

      - name: Typecheck reigns
        working-directory: ./elements/reigns
        run: npm run check:types

      - name: Build kahoot-controller
        working-directory: ./elements/kahoot-controller
        run: npm i
      - name: ls
        working-directory: ./elements/kahoot-controller
        run: ls -alh src/
      - name: Build kahoot-controller
        working-directory: ./elements/kahoot-controller
        run: npm run build
